spring:
  profiles:
    active: local
  mongodb:
    embedded:
      version: 3.5.5
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [google client id]
            client-secret: [google client secret key]

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #        include: health,info
        include: '*'
  info:
    env:
      enabled: true
info:
  project.version: '${version}'
  java.version: '${sourceCompatibility}'

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: info
    web: info
#    reactor: debug
#    org.springframework.data: debug
#    org.springframework.messaging: debug
#    org.springframework.amqp: debug
