spring:
  profiles:
    active: local
  mongodb:
    embedded:
      version: 3.5.5
  webflux:
    hiddenmethod:
      filter:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: info
    web: debug
    reactor.netty: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
